In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


2023-08-09 18:34:39.103881: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-09 18:34:39.783099: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-08-09 18:34:39.787577: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-09 18:34:41.796807: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [12]:
one_hot("amazing restaurant",30)

[29, 25]

In [15]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[22, 12], [29, 25], [28, 19], [7, 12, 28], [14, 27, 2], [8, 12], [7, 27, 27], [20, 13], [20, 14], [16, 21]]


In [17]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[22 12  0]
 [29 25  0]
 [28 19  0]
 [ 7 12 28]
 [14 27  2]
 [ 8 12  0]
 [ 7 27 27]
 [20 13  0]
 [20 14  0]
 [16 21  0]]


In [18]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [19]:
X = padded_reviews
y = sentiment

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [21]:
model.fit(X, y, epochs=50, verbose=0)

In [22]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 161ms/step - loss: 0.6089 - accuracy: 1.0000


1.0

In [24]:
weights = model.get_layer('embedding').get_weights()[0]
weights ,len(weights)

(array([[ 0.03236542,  0.06477103,  0.09547648, -0.08274522, -0.07061965],
        [ 0.00627177,  0.01322332,  0.00360274, -0.03108301, -0.03056889],
        [-0.02096195, -0.0024853 , -0.07161245,  0.07221312,  0.06774015],
        [ 0.02991779, -0.01268015,  0.025845  ,  0.02927537, -0.00904145],
        [-0.02896817,  0.02329225,  0.03618724,  0.02790527,  0.00847606],
        [ 0.02536431, -0.0157652 , -0.01409587,  0.01872284, -0.01916599],
        [ 0.04099298, -0.01870661, -0.00909613,  0.04619188,  0.04571014],
        [-0.00982047, -0.01898352, -0.01418165, -0.00294011, -0.02435246],
        [-0.06431267,  0.07069755, -0.06468374, -0.03968975, -0.02878605],
        [-0.01203927,  0.00736169, -0.00716916,  0.01084222, -0.00284366],
        [-0.03320636,  0.02140174, -0.01662811,  0.02957949, -0.00850094],
        [ 0.03738729,  0.04072801,  0.02925504,  0.03808757,  0.04551346],
        [ 0.01719288, -0.05125578, -0.07507242,  0.06460961,  0.01612989],
        [-0.06861306,  0.

In [25]:
weights[13]

array([-0.06861306,  0.01995276,  0.07110431, -0.06585646, -0.0971133 ],
      dtype=float32)

In [26]:
weights[4]

array([-0.02896817,  0.02329225,  0.03618724,  0.02790527,  0.00847606],
      dtype=float32)

In [27]:
weights[16]

array([-0.07021691,  0.01364459, -0.0979899 , -0.07967012, -0.0040867 ],
      dtype=float32)