# DropOut layer

![more details](https://www.notion.so/Dropout-Layer-8a34691c4c4d4775860897bd5e767f98)
![drop](dropout.png)

In [56]:
from tensorflow import keras
import pandas as pd
import numpy as np

In [57]:
df = pd.read_csv('sonar_dataset.csv', header=None)

In [58]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [59]:
df.shape

(208, 61)

In [60]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [61]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [62]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   

       57      58      59  
0  0.0084  0.0090  0.0032  
1  0.0049  0.0052  0.0044  
2  0.0164  0.0095  0.0078  
3  0.0044  0.0040  0.0117  
4  0.0048  0.0107  0.0094  

[5 rows x 60 columns]

In [63]:
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [64]:
y = pd.get_dummies(y , drop_first=True , dtype=np.int64)
y.sample(5)

R
81  1
49  1
76  1
96  1
83  1

In [65]:
y.value_counts()

R
0    111
1     97
Name: count, dtype: int64

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42 )

In [67]:
X_train.shape , y_train.shape

((166, 60), (166, 1))

In [68]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation='relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid'),
    
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [69]:
model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100


21/21 [==============================] - 1s 3ms/step - loss: 0.6954 - accuracy: 0.4940
Epoch 2/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6804 - accuracy: 0.6446
Epoch 3/100
21/21 [==============================] - 0s 4ms/step - loss: 0.6676 - accuracy: 0.6325
Epoch 4/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6485 - accuracy: 0.7108
Epoch 5/100
21/21 [==============================] - 0s 3ms/step - loss: 0.6176 - accuracy: 0.7169
Epoch 6/100
21/21 [==============================] - 0s 3ms/step - loss: 0.5860 - accuracy: 0.7108
Epoch 7/100
21/21 [==============================] - 0s 2ms/step - loss: 0.5500 - accuracy: 0.6988
Epoch 8/100
21/21 [==============================] - 0s 2ms/step - loss: 0.5200 - accuracy: 0.7349
Epoch 9/100
21/21 [==============================] - 0s 3ms/step - loss: 0.4843 - accuracy: 0.7892
Epoch 10/100
21/21 [==============================] - 0s 3ms/step - loss: 0.4631 - accuracy: 0.7831
Epoch 11/100
21/21 [=

In [70]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.4581 - accuracy: 0.8810


[0.4580867290496826, 0.8809523582458496]

In [71]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])
print(y_pred.shape)

# round up the prediction
y_pred = np.round(y_pred).astype(int)
print(y_pred)

2/2 [==============================] - 0s 3ms/step
[1.2536809e-07 9.9988896e-01 3.4333429e-01 9.9969214e-01 3.4713940e-04
 3.4176925e-01 4.6909556e-01 2.7429458e-01 9.9999887e-01 3.5832196e-03]
(42,)
[0 1 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1 0 0 0 0
 0 1 0 1 1]


In [72]:
y_test.values[:10]

array([[0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [73]:
from sklearn.metrics import confusion_matrix ,classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[23  3]
 [ 2 14]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90        26
           1       0.82      0.88      0.85        16

    accuracy                           0.88        42
   macro avg       0.87      0.88      0.88        42
weighted avg       0.88      0.88      0.88        42



## Using Dropout Layers

In [77]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.4),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation='sigmoid'),
    
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100


21/21 [==============================] - 5s 20ms/step - loss: 0.7158 - accuracy: 0.5000
Epoch 2/100
21/21 [==============================] - 0s 17ms/step - loss: 0.7036 - accuracy: 0.4940
Epoch 3/100
21/21 [==============================] - 0s 9ms/step - loss: 0.7036 - accuracy: 0.4578
Epoch 4/100
21/21 [==============================] - 0s 15ms/step - loss: 0.6872 - accuracy: 0.5361
Epoch 5/100
21/21 [==============================] - 0s 12ms/step - loss: 0.6868 - accuracy: 0.5060
Epoch 6/100
21/21 [==============================] - 0s 10ms/step - loss: 0.6874 - accuracy: 0.5301
Epoch 7/100
21/21 [==============================] - 0s 9ms/step - loss: 0.6801 - accuracy: 0.5723
Epoch 8/100
21/21 [==============================] - 0s 10ms/step - loss: 0.6867 - accuracy: 0.5542
Epoch 9/100
21/21 [==============================] - 0s 11ms/step - loss: 0.6883 - accuracy: 0.5843
Epoch 10/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6715 - accuracy: 0.6506
Epoch 11/100
2

In [78]:
model.evaluate(X_test, y_test)


2/2 [==============================] - 0s 16ms/step - loss: 0.2867 - accuracy: 0.9048


[0.2867337167263031, 0.9047619104385376]

In [79]:
y_pred = model.predict(X_test).reshape(-1)
print(y_pred[:10])
print(y_pred.shape)

# round up the prediction
y_pred = np.round(y_pred).astype(int)
print(y_pred)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

2/2 [==============================] - 0s 9ms/step
[0.00239982 0.9938974  0.8007834  0.9757272  0.00405498 0.7983304
 0.17701924 0.50450057 0.9999555  0.04124206]
(42,)
[0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0
 0 1 0 1 1]
[[24  2]
 [ 2 14]]
              precision    recall  f1-score   support

           0       0.92      0.92      0.92        26
           1       0.88      0.88      0.88        16

    accuracy                           0.90        42
   macro avg       0.90      0.90      0.90        42
weighted avg       0.90      0.90      0.90        42

